### PR TITLE
Pull Request 2

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Minimums simulation, hydraulics bugfixes, static system improved.

### CODE REVIEW

**Review by zakalawe — COMMENTED** [review]
Hmm, maybe our workflow is messed up, did you mean to include this in the Pull request?

**Review by zakalawe — APPROVED** [review]
Okay, this all looks good I think!

**Comment by legoboyvdlp** [comment]
Have you any more requests?

**Comment by zakalawe** [comment]
Not right now thanks, I'm working on lots of integration niggles and 'real' stuff - paint and carpet and wiring :)

**Comment by zakalawe** [comment]
Okay, the other thing which is possible you could do is the lower EICAS - since I just go the RaspberryPi for this working. (And the LCD). The catch is I don't have the hardware buttons to select the display (ENG / HYD buttons) working, but having the secondary engine parameters would be cool.

This is probably a lot of work however, unless you can find / re-use pieces from other places?

**Comment by legoboyvdlp** [comment]
The 737-800YV has this implemented - let me see if I can port it over :smile:

**Pull request merged**
