### PR TITLE
Add lower EICAS

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Adds Lower EICAS from 737-800YV

I'm not sure if oil pressure is in JSBSIM anywhere unfortunately. I don't think so.

### CODE REVIEW

**Review by zakalawe — CHANGES_REQUESTED** [review]
The EFIS, EFIS>bak and screen-test files seem unused to me? Otherwise looks great!

**Comment by legoboyvdlp** [comment]
The EFIS.ac file and screen-test texture is required to map the canvas onto. I can remove that .bak.

**Comment by zakalawe** [comment]
But then, why is it called EFIS - surely that's the unit next to the MCP on the glareshield? Why isn't it called Lower_EICAS.ac or ForwardPedestal.ac? Maybe I'm just worrying too much :)

**Comment by legoboyvdlp** [comment]
I think technically EFIS is the entire set of displays, but regardless, I'll rename the file :)

**Comment by zakalawe** [comment]
I mean I think at this point I'm just being awkward - I think of the EFIS as being the controls but technically you are probably right. Anyway, do what you think best :)

**Pull request merged**
