### PR TITLE
Improve 3D model of ISFD, add assumed temperature

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Hi,
This fixes the baro knob ISFD and makes it smoother, fixes the texture of the N1 limit knob (in preparation to make it work in the future), and makes the MFD buttons mesh instead of just a flat texture.

image

image

I also added assumed temperature display on the EICAS:
image

However, I have a very strange error:

> Nasal runtime error: No such member: setText
  430.33 [ALRT]:nasal        at C:/Users/redpa/Documents/FlightGear/Custom Aircraft/737-800/Models/Instruments/EICAS/upperEICAS.nas, line 89
  430.33 [ALRT]:nasal        called from: C:/Users/redpa/Documents/FlightGear/Custom Aircraft/737-800/Models/Instruments/EICAS/upperEICAS.nas, line 45

I've no idea what is causing this -- "assumeTemp" is in the SVG keys and is in the .svg file. 

Have you ever seen this one before?

### CODE REVIEW

**Comment by zakalawe** [comment]
Awesome, thanks!

**Comment by legoboyvdlp** [comment]
@zakalawe the changes possibly broke master - there is a breaking nasal error.
Sorry, I should have been clear that I was looking for feedback as how to resolve the nasal error before merging.

Specific nasal error:
`Nasal runtime error: No such member: setText
430.33 [ALRT]:nasal at C:/Users/redpa/Documents/FlightGear/Custom Aircraft/737-800/Models/Instruments/EICAS/upperEICAS.nas, line 89
430.33 [ALRT]:nasal called from: C:/Users/redpa/Documents/FlightGear/Custom Aircraft/737-800/Models/Instruments/EICAS/upperEICAS.nas, line 45`

I did add it to the SVG keys and it exists in the .svg file...

**Comment by zakalawe** [comment]
Oh sorry, my bad for not checking. I will take a look at the error!

**Comment by zakalawe** [comment]
I'm not seeing the assumed temp, but also not seeing the error - do I need to do something to trigger it?

**Comment by legoboyvdlp** [comment]
Not too sure - I'll check again.
Assumed temperature should be visible when instrumentation/fmc/inputs/assumed-temp-deg-c has a value?

**Comment by zakalawe** [comment]
Okay, for some reason the assumeTemp element gets turned into a group, with <text> children. Is there anything special about it? Something is confusing the Nasal / Canvas SVG parser but I can't see why it's different.

**Comment by zakalawe** [comment]
> Okay, for some reason the assumeTemp element gets turned into a group, with children. Is there anything special about it? Something is confusing the Nasal / Canvas SVG parser but I can't see why it's different.

Right, it's the multiple/nested tspan children which throw it off, removing them and everything works as expected.

**Comment by legoboyvdlp** [comment]
It shouldn't 😕 

Thanks for fixing - feel free to push it, as I'm not honestly sure what exactly you mean by tspan children.

**Comment by zakalawe** [comment]
Fix is pushed now!

**Comment by legoboyvdlp** [comment]
Many thanks!

**Pull request merged**
