### PR TITLE
Add electrical system from 737-800YV

### PR DESCRIPTION
**Pull request by legoboyvdlp**
- Added electrical system (including APU )

### CODE REVIEW

**Comment by zakalawe** [comment]
Oooh, interesting. I will likely merge this after FSWeekend because I don't have the overhead panel in my simpit anyway, and it seems to touch /all/ the displays? But maybe there is some stuff worth merging?

Everything else is looking great btw, will post some videos from FSWeekend!

**Comment by legoboyvdlp** [comment]
Great 😃 

All it is doing to the displays is overlaying a black object above the object where the canvas is displayed, thus hiding them. In fact, I don't think it will turn off the displays if you are showing the canvas on a seperate screen, depending on how you are showing the displays in your cockpit.

**Comment by zakalawe** [comment]
> Great 😃
> 
> All it is doing to the displays is overlaying a black object above the object where the canvas is displayed, thus hiding them. In fact, I don't think it will turn off the displays if you are showing the canvas on a seperate screen, depending on how you are showing the displays in your cockpit.

Yeah that won't hide anything for remove-canvas - we would need to add a top-level 'disabled' flag or something to Canvases to do this nicely.

**Comment by legoboyvdlp** [comment]
One thing I didn't do is add the warnings for the electrical system. I'll see if that is possible.

I'm not really sure about hiding the remote canvas - would you be able to do that on your side?

**Comment by legoboyvdlp** [comment]
I'm reworking the electrical system at the moment - please don't merge yet - Thanks!

**Comment by legoboyvdlp** [comment]
Sorry for the delay: I've found a stubborn bug in the bus transfer logic, which I am having difficulty in solving :confused:

I will try and get this finished by the end of next week.

**Comment by zakalawe** [comment]
Don’t worry about the delay, I have twenty other thighs I’m working on. But, if you want another person to look for the bug, just give me a hint to start. No promises but a second opinion is often nice :)

**Comment by legoboyvdlp** [comment]
I _think_ it's ready... but I would appreciate any testing or feedback ;)

**Review by zakalawe — APPROVED** [review]
Cool, looks good to me to merge (will test in detail in the coming weeks)

**Comment by legoboyvdlp** [comment]
Great! Thanks :smiley:

**Comment by legoboyvdlp** [comment]
The dragging animations for the electrical system switches (particularly the generators) are a bit dodgy. Sometimes you try to drag it down and it goes up. I think it's because the switches are mounted at a sort of 45 degree angle to the pilot.


If there is nothing else I think I'll possibly do some work on the 3D side - some of the switches are scaled wrongly (e.g. fuel panel) and many are missing completely! 

As for turning the Canvas displays off 'properly', there are three things:
a) the PFDs really need split into two seperate ones. I can't remember off the top of my head, but they are definitely on different two electrical sources, if you are battery only you will only have the captain's side PFD. I'll look up the specific sources once I get home.

b) the IFSD needs connected to the electrical system. I'll look up the source as soon as I get home.

c) the displays really need turned off properly, as you said with a flag? I'm not really sure how to do this unfortunately.

**Comment by zakalawe** [comment]
Ooh switches at 45-degree angle are a funny one, the dragging logic is optimised for switches aligned roughly with a major axis. So indeed I can imagine some strange things happening in that case.

For the canvases, if you can ensure there's an /instruments/<foo>/powered flag I can look at, this would be sufficient. I don't think its worth adding an actual canvas feature to enable/disable them, this is really a simulation feature.

For the ISFD, I need to write a real controller for the 737: ie real separate altimeter source, heading source, etc. And then ensure these are powered by the correct source (internal battery I believe) for the ISFD.

One thing you could do there is create a 3D bezel model for the ISFD, including the buttons and altimeter setting knob. Since my 3D modelling skills are terrible :)

I need to add the LOC / GS mode bars to the display, but I can do that quite easily, and then the ISFD is close to complete I think.

**Pull request merged**
