### PR TITLE
Add ISFD 3D model

### PR DESCRIPTION
**Pull request by legoboyvdlp**
image

I'm really not sure how to add the actual canvas display to this - the screen is uvmapped and has a texture, so it should be possible according to the wiki.

### CODE REVIEW

**Comment by zakalawe** [comment]
That looks awesome, I'll merge it once I'm home and add the ISFD to it.

**Comment by legoboyvdlp** [comment]
I should animate it as well, I think. 

In ISFD-install.nas, I can add functions for the actions of the buttons, which you can use to interface with the instrument?

**Comment by zakalawe** [comment]
Animations would be good, but I'm still working out the file structure: ISFD-install.nas is a reasonable place for now indeed.

**Comment by legoboyvdlp** [comment]
image

**Comment by zakalawe** [comment]
Are you okay for me to merge this now? Or more changes coming?

**Comment by legoboyvdlp** [comment]
Yep, that's absolutely fine - I don't think I've anything else. Thanks!

**Pull request merged**
