### PR TITLE
Flight controls: correction for error in flight spoilers

### PR DESCRIPTION
**Pull request by legoboyvdlp**

### CODE REVIEW

**Comment by zakalawe** [comment]
@legoboyvdlp Minor issue: the version here is /not/ what's in FGaddon. So maybe we need to fix it there as well?

**Comment by legoboyvdlp** [comment]
Sure, that's fine.

**Comment by legoboyvdlp** [comment]
@zakalawe How do you want to do this? Can you merge back from fgaddon to here?

And isn't the correct upstream source of fgaddon actually soitanen's repository?

**Comment by zakalawe** [comment]
Yes, for FGaddon it's Soitanen's repo. We should maybe have a conversation with him about to handle this, my changes here are mostly customisations for the sim-pit, anything which 'everyone' wants such as the FMS/CDU work, should go upstream.

**Comment by legoboyvdlp** [comment]
Ah, ok. In that case I'll leave it open here for now.

**Comment by legoboyvdlp** [comment]
Remodelled the flap lever and corrected the animation such that the positions match the texture. I'm not sure what the status is - so this should go to fgaddon or?

**Comment by zakalawe** [comment]
This has been hanging around far too long. Let's try to upstream all the 737-800 changes from this to the real 737-800, and I can rebase on top? I don't know how many other fixes you made?

**Comment by legoboyvdlp** [comment]
There's just one other minor fix to the flap lever - remodelled and corrected the degree angles. Go ahead with anything you want to do, I don't have anything at the moment!

**Comment by zakalawe** [comment]
Merged to the branch for upstreaming, finally.

**Pull request closed without merging**
